from pathlib import Path
import json,sqlite3,sys,hashlib,shutil,importlib.util,copy,subprocess
r=Path('/home/ubuntu/unreal-auditor');w=r/'review-continuity-workspace';stage=w/'review-continuity-20260913-v1';sys.path.insert(0,str(stage))
with (w/'out/service-tests.log').open('w') as f:subprocess.run(['python3','-m','unittest','discover','-s','tests','-q'],cwd=stage,stdout=f,stderr=subprocess.STDOUT,check=True)
from server import Store
src=sqlite3.connect('file:'+str(r/'review-service/state/review.sqlite3')+'?mode=ro',uri=True);path=w/'out/verification.sqlite3'
with sqlite3.connect(path) as dst:src.backup(dst)
src.close();path.chmod(0o600);manifest=json.loads((stage/'tasks.json').read_text());store=Store(path,manifest,mode='external',tokens={'qa':{'id':'qa','reviewer':'QA'}},runner=['/usr/bin/true'],build_sha='f'*64)
owner=store.db.execute("select owner from sessions where lower(reviewer)='qiucheng' limit 1").fetchone()[0];user={'owner':owner};before=hashlib.sha256(str([tuple(x) for x in store.db.execute('select * from feedback order by rowid')]).encode()).hexdigest();reviews=store.reviews(user);expected={'B01','B02','B03'}|{f'S{i:02}' for i in range(1,10)};assert set(reviews)==expected,set(reviews)
d=store.dashboard(user);rows=[t for t in d['tasks'] if t['id'] in expected];assert all(x['reviews']>=1 for x in rows);assert next(t for t in rows if t['id']=='S05')['my_quality']=='uncertain'
assert before==hashlib.sha256(str([tuple(x) for x in store.db.execute('select * from feedback order by rowid')]).encode()).hexdigest();history=store.review_history(user);report=dict(status='PASS',qiucheng_tasks=sorted(reviews),qiucheng_latest_tasks=len(reviews),qiucheng_feedback_records=store.db.execute('select count(*) from feedback where owner=?',(owner,)).fetchone()[0],qiucheng_history_records=len(history),feedback_unmodified=True,no_inferred_second_reviewer=True);store.db.close();(w/'out/data-verification.json').write_text(json.dumps(report,indent=2))
spec=importlib.util.spec_from_file_location('sup',stage/'runtime/mac_supervisor.py');mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod);cfg=json.loads((stage/'candidate-runtime.json').read_text());cfg.update(manifest=str(stage/'tasks.json'),state_dir=str(w/'out/runtime'));sup=mod.Supervisor(cfg);assert sup.capacity==3;(w/'out/runtime-validation.json').write_text(json.dumps(dict(status='PASS',capacity=sup.capacity,profiles=len(sup.allowed))));print(json.dumps(report))
