/* Real HTTPS + Pixel Streaming acceptance. Credentials stay in an external file. */
const {chromium} = require('playwright');
const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
const accounts = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const out = process.argv[3];
fs.mkdirSync(out, {recursive: true});
const report = {started: new Date().toISOString(), checks: [], errors: []};
const check = (name, detail = true) => { report.checks.push({name, detail}); console.log(name + ': ' + JSON.stringify(detail)); };
const exploreURL = 'https://explore.150-230-45-149.sslip.io';
const evaluateURL = 'https://evaluate.150-230-45-149.sslip.io';
let browser;
async function login(page, origin, name) {
  await page.goto(origin, {waitUntil: 'networkidle'});
  await page.locator('#login-name').fill(name);
  await page.locator('#login-password').fill(accounts[name]);
  await page.locator('#login-submit').click();
  await page.locator('#workspace').waitFor({state: 'visible'});
}
(async () => {
  browser = await chromium.launch({channel: 'chrome', headless: process.env.BF_HEADED !== '1', args: ['--autoplay-policy=no-user-gesture-required']});
  const context = await browser.newContext({viewport: {width: 1512, height: 1100}});
  const explorer = await context.newPage();
  await explorer.bringToFront();
  explorer.on('pageerror', error => { report.errors.push('exploration: ' + error.message); console.log('PAGE ERROR', error.message); });
  await login(explorer, exploreURL, 'qa-explorer');
  check('Explorer login');
  await explorer.locator('.progress-table button').first().click();
  const workspace = await explorer.evaluate(() => fetch('/api/workspace').then(r => r.json()));
  if (workspace.attempt?.status !== 'draft') { await explorer.locator('#new-attempt').click(); }
  const publicJSON = JSON.stringify(await explorer.evaluate(() => fetch('/api/workspace').then(r => r.json())));
  assert(!/rubric|bench|悬空|60 cm|S01|build_sha256|\/Game\//i.test(publicJSON));
  check('Public task has no ground truth');
  const evaluationAccess = await context.request.get(evaluateURL + '/api/queue');
  assert.equal(evaluationAccess.status(), 401); check('Explorer identity cannot enter evaluation');
  const previousFlags = await explorer.locator('#flags .flag').count();
  if (await explorer.locator('#start').isEnabled()) await explorer.locator('#start').click();
  await explorer.locator('#player iframe').waitFor({timeout: 120000});
  const iframe = await explorer.locator('#player iframe').elementHandle();
  const game = await iframe.contentFrame();
  await explorer.screenshot({path: path.join(out, 'stream-connecting.png'), fullPage: true});
  await game.waitForFunction(() => { const video = document.querySelector('video'); return video && video.videoWidth > 0 && video.readyState >= 2; }, null, {timeout: 90000});
  check('Real Unreal video connected', await game.evaluate(() => { const video = document.querySelector('video'); return {width: video.videoWidth, height: video.videoHeight, paused: video.paused, health: window.reviewHealth}; }));
  await game.waitForFunction(() => window.reviewHealth?.frames > 40, null, {timeout: 30000});
  await game.locator('video').click();
  await game.waitForFunction(() => document.pointerLockElement === document.querySelector('video')?.parentElement, null, {timeout: 10000});
  await explorer.keyboard.down('w');
  await explorer.waitForTimeout(1000);
  await explorer.keyboard.up('w');
  await game.waitForFunction(() => window.reviewHealth?.keysSent >= 2);
  check('Physical movement keys reach Unreal', await game.evaluate(() => ({keysSent: window.reviewHealth.keysSent, pointerLocked: !!document.pointerLockElement})));
  await explorer.mouse.move(700, 650);
  await explorer.mouse.move(940, 650, {steps: 20});
  await explorer.waitForTimeout(2000);
  await explorer.screenshot({path: path.join(out, 'exploration-live.png'), fullPage: true});
  // Physical keyboard Flag inside the actual player iframe.
  await game.locator('video').click();
  await explorer.keyboard.press('f');
  await explorer.waitForFunction(n => document.querySelectorAll('#flags .caption').length > n && [...document.querySelectorAll('#flags .caption')].some(e => e.textContent.includes('已保存')), previousFlags, {timeout: 20000});
  check('F key saves real video evidence');
  await explorer.keyboard.press('Escape');
  await explorer.locator('#add-report').click();
  const description = '技术验收样例：我观察到场景中的物体与地面的支撑关系异常，截图记录了当前探索视角。此记录仅用于验证探索到人工评测的流程。';
  await explorer.locator('#reports textarea').last().fill(description);
  // Typing the letter f in a description must not add another flag.
  const flagCount = await explorer.locator('#flags .flag').count();
  await explorer.locator('#reports textarea').last().press('f');
  await explorer.locator('#reports textarea').last().fill(description);
  await explorer.locator('#reports .report').last().locator('input[type=checkbox]').last().check();
  await explorer.waitForFunction(() => document.querySelector('#save-status').textContent === '草稿已保存');
  assert.equal(await explorer.locator('#flags .flag').count(), flagCount); check('Flag suppressed while typing');
  await explorer.reload({waitUntil: 'networkidle'});
  await explorer.locator('.progress-table button').first().click();
  await explorer.locator('#reports textarea').last().waitFor();
  assert.equal(await explorer.locator('#reports textarea').last().inputValue(), description); check('Draft and evidence survive reload');
  const reconnected = await (await explorer.locator('#player iframe').elementHandle()).contentFrame();
  await reconnected.waitForFunction(() => document.querySelector('video')?.readyState >= 2, null, {timeout: 30000});
  await explorer.screenshot({path: path.join(out, 'exploration-report.png'), fullPage: true});
  await explorer.locator('#submit').click();
  await explorer.locator('#submitted').waitFor({state: 'visible'});
  await explorer.waitForFunction(() => document.querySelector('#submitted').textContent.includes('已送达'), null, {timeout: 30000});
  const submitted = await explorer.evaluate(() => fetch('/api/workspace').then(r => r.json()));
  const sid = submitted.attempt.submission.id; check('Final answer delivered', sid);
  const evaluator = await context.newPage();
  evaluator.on('pageerror', error => report.errors.push('evaluation: ' + error.message));
  await login(evaluator, evaluateURL, 'qa-evaluator');
  await evaluator.locator('.progress-table tr').filter({hasText: sid.slice(0, 8).toUpperCase()}).getByRole('button').click();
  await evaluator.locator('#evaluation').waitFor({state: 'visible'});
  assert((await evaluator.locator('#rubric').innerText()).length > 30);
  assert((await evaluator.locator('#answers').innerText()).includes(description));
  await evaluator.locator('#answers img').first().waitFor();
  await evaluator.locator('#answers img').first().evaluate(img => img.complete && img.naturalWidth > 0 ? Promise.resolve() : new Promise((resolve, reject) => {img.onload = resolve; img.onerror = reject;}));
  assert(await evaluator.locator('#answers img').first().evaluate(img => img.complete && img.naturalWidth > 0));
  check('Evaluator sees exact query, rubric, description and copied evidence');
  await evaluator.locator('#answers select[aria-label^="判定 "]').last().selectOption('insufficient');
  await evaluator.locator('#answers textarea').last().fill('技术验收记录：成功查看 query、版本化 rubric、探索者描述和截图。样例描述不作正式缺陷结论。');
  for (const field of await evaluator.locator('#answers select[aria-label^="类别复核 "]').all()) await field.selectOption('uncertain');
  await evaluator.locator('#save').click();
  await evaluator.waitForFunction(() => document.querySelector('#message').textContent.includes('人工判定已保存'));
  check('Human judgment saved');
  await evaluator.screenshot({path: path.join(out, 'evaluation-saved.png'), fullPage: true});
  const explorerAfter = await explorer.evaluate(() => fetch('/api/workspace').then(r => r.json()));
  assert.equal(explorerAfter.attempt.status, 'submitted');
  const runtime = await explorer.evaluate(aid => fetch('/api/attempts/' + aid + '/runtime').then(r => r.json()), submitted.attempt.id);
  check('Runtime released after submission', runtime.status);
  assert.equal(runtime.status, 'idle');
  assert.deepEqual(report.errors, []);
  report.success = true;
})().catch(error => { report.success = false; report.failure = error.stack; console.error(error); process.exitCode = 1; }).finally(async () => {
  report.finished = new Date().toISOString(); fs.writeFileSync(path.join(out, 'browser-report.json'), JSON.stringify(report, null, 2));
  if (browser) await browser.close();
});
