import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../web/shared/case-progress.js',import.meta.url),'utf8');
const {caseStatus,groupCases}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const base={id:'case-one',title:'World',assigned_explorers:5,completed_explorers:3,active_explorers:0,submitted_answers:3,received_answers:3,reviewed_answers:2,active_reviews:0,reviewer_count:1};
const records=[{id:'answer-a',task_id:'case-one',owner:'one'},{id:'answer-b',task_id:'old-version',case_progress:{id:'case-one'},owner:'two'}];
const result=groupCases({cases:[base,{...base,id:'empty-case',completed_explorers:0,submitted_answers:0,received_answers:0,reviewed_answers:0}]},records);
assert.equal(result.length,2);assert.equal(result[0].records.length,2);assert.equal(result[0].completed_explorers,3);assert.equal(result[0].reviewer_count,1);assert.equal(result[1].records.length,0);
assert.equal(caseStatus(base),'待复核');
assert.equal(caseStatus({...base,reviewed_answers:3}),'当前答案已复核');
assert.equal(caseStatus({...base,completed_explorers:1,submitted_answers:1,received_answers:1,reviewed_answers:1,active_explorers:4}),'当前答案已复核');
assert.equal(caseStatus({...base,assigned_explorers:null,reviewed_answers:3}),'当前答案已复核');
assert.equal(caseStatus({...base,completed_explorers:5,submitted_answers:5}),'答案同步中');
assert.equal(caseStatus({...base,completed_explorers:5,submitted_answers:5,received_answers:5}),'待复核');
assert.equal(caseStatus({...base,completed_explorers:5,submitted_answers:5,received_answers:5,active_reviews:1}),'复核中');
assert.equal(caseStatus({...base,completed_explorers:5,submitted_answers:5,received_answers:5,reviewed_answers:5}),'当前答案已复核');
assert.equal(caseStatus({...base,reviewed_answers:null}),'统计暂不可用');
assert.equal(caseStatus(result[1]),'未开始');
assert.equal(caseStatus({...result[1],skipped_explorers:1}),'待继续探索');
assert.equal(groupCases({cases:[base]},[{id:'secret',task_id:'not-authorized'}])[0].records.length,0);
console.log('Case grouping, version mapping, empty cases, completion and permissions: passed');
