from pathlib import Path
root=Path(__file__).resolve().parents[1];src=root/'project/Plugins/AuditorRuntime/Source/AuditorRuntime/Private'
p=src/'AuditorReviewSwitch.cpp';s=p.read_text();line='    if (FString(FApp::GetProjectName()) == TEXT("RuralAustralia")) Maps={TEXT("/Game/Auditor/RuralAustralia/RoadBend"),TEXT("/Game/Auditor/RuralAustralia/Roadside"),TEXT("/Game/Auditor/RuralAustralia/Canyon")};\n'
if line not in s:s=s.replace('    bool ValidTask = Task == TEXT("baseline");',line+'    bool ValidTask = Task == TEXT("baseline");');p.write_text(s)
p=src/'AuditorTasks.cpp';s=p.read_text();s=s.replace('FVector Center = TargetCenter();\n        Center.Z = Pawn->GetActorLocation().Z;', 'FVector Center = VectorField(Spec, TEXT("collision_center"), TargetCenter());\n        Center.Z = Pawn->GetActorLocation().Z;');p.write_text(s)
print('RURAL_RUNTIME_PATCHED')

p=src/'AuditorTasks.cpp';s=p.read_text();old='        const bool Removed = !HitsTarget();\n        Target->SetActorEnableCollision(true);\n        const bool BaselineHit = HitsTarget();\n        Target->SetActorEnableCollision(false);\n        FinishTest(BaselineCollision && BaselineHit && Removed, TEXT("Target capsule hits baseline geometry; injected target permits passage"));';new='        if (TestPhase == 0)\n        {\n            TestFirstState = !HitsTarget();\n            Target->SetActorEnableCollision(true);\n            TestPhase = 1; PhaseAge = 0;\n            return;\n        }\n        if (PhaseAge < 0.2f) return;\n        const bool BaselineHit = HitsTarget();\n        Target->SetActorEnableCollision(false);\n        UE_LOG(LogTemp, Display, TEXT("AUDITOR_COLLISION_PROBE baseline_enabled=%d baseline_hit=%d removed=%d center=%s authored_center=%d"), BaselineCollision, BaselineHit, TestFirstState, *Center.ToString(), Spec->HasField(TEXT("collision_center")));\n        FinishTest(BaselineCollision && BaselineHit && TestFirstState, TEXT("Target capsule hits baseline geometry; injected target permits passage"));'
if old in s:s=s.replace(old,new);p.write_text(s)
