"""VLA explorer on the Unreal environments (local A10): Open-P2P drives a paused Unreal build through the AuditorRemote
step interface (the `environments/server.py` backend of the iclr branch, used in-process - no HTTP).  One 50 ms
tick = the P2P action converted into `turn` / `look` / `move_up` / `move_down` / `idle` steps; the world only advances
inside those steps, so a tick is exactly 50 ms of simulated time on any device (30 Hz fixed physics, paused between
steps).  Records a full frame every N ticks, poses per tick, meta.json and a video - the same layout as
agent/vla/vla_explore.py for the three.js pages.

Usage:
  .venv/bin/python -m agent.vla.vla_ue --tasks S01,H03 --ticks 1200 --tag vla-ue      (or --tasks @file with one id per line)
Inputs: --profiles out/runtime/unreal-profiles.json, generated by the environment downloader.
"""
import argparse
import base64
import io
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parents[2]
from agent.vla.vla_explore import P2PClient, KEYMAP, MAX_MOUSE_PX

sys.path.insert(0, str(REPO))
from environments.server import UnrealBackend, APIError  # noqa: E402

DEG_PER_PX = 180.0 / (600.0 * 3.141592653589793)   # the three.js pages turn 1/600 rad per mouse pixel; same mapping here
WALK_CM_PER_TICK = 11                                # 220 cm/s walker x 50 ms
RES = os.environ.get("VLA_UE_RES", "960x540")        # offscreen render size (the VLM harness uses 960x540; the policy sees 192x192 either way)
FREEZE = os.environ.get("VLA_UE_FREEZE", "1") == "1"  # SIGSTOP the game while the policy thinks: a paused game renders in a tight loop
                                                       # (fixed time step, t.MaxFPS is ineffective) and several instances saturate the GPU
MAXFPS = os.environ.get("VLA_UE_MAXFPS")              # replaces the profile's "t.MaxFPS 30" (wall-clock render cap only: the plugin runs a fixed
                                                       # time step, so frames per step and the observation are the same; a paused game keeps
                                                       # rendering at the cap, which is what saturates the GPU with several instances)


class TaskBackend(UnrealBackend):
    """Launch the family build on the task's map (like the review site's runtime) and reset into the task."""

    def __init__(self, binary, map_name, task, arguments, root, label=None, remote_task=None):
        """remote_task: per-task maps (Urban) carry no ?Task= option; the IPC-fixed builds take the task id through
        -AuditorRemoteTask and in the reset command instead (the review runtime's PinnedBackend does the same)."""
        import tempfile, uuid
        self.root = Path(tempfile.mkdtemp(prefix=f"ep-{label or task or map_name.rsplit('/', 1)[-1]}-", dir=root))
        self.log = (self.root / "unreal.log").open("wb")
        self.map_name, self.task = map_name, task
        resx, resy = RES.split("x")
        argv = [binary, map_name + ("?Task=" + task if task else ""), "-RenderOffscreen", "-windowed", f"-ResX={resx}", f"-ResY={resy}",
                "-unattended", "-nosound", "-AuditorServe", "-AuditorIPC=" + str(self.root)]
        if remote_task:
            argv += ["-AuditorRemoteTask=" + remote_task, "-abslog=" + str(self.root / "native.log"), "-forcelogflush"]
        argv += list(arguments)
        (self.root / "argv.json").write_text(json.dumps(argv))
        self.process = subprocess.Popen(argv, stdout=self.log, stderr=subprocess.STDOUT, start_new_session=True)

    def png(self):
        return (self.root / "observation.png").read_bytes()

    def freeze(self):
        if FREEZE and self.process.poll() is None:
            os.kill(self.process.pid, signal.SIGSTOP)

    def thaw(self):
        if self.process.poll() is None:
            try: os.kill(self.process.pid, signal.SIGCONT)
            except ProcessLookupError: pass

    def close(self):
        self.thaw()
        super().close()

    def log_text(self):
        """stdout capture + the plugin's own native.log in the IPC dir (AUDITOR_EXPLORATION_READY / AUDITOR_OUT_OF_BOUNDS_RESET lines)."""
        out = ""
        for name in ("unreal.log", "native.log"):
            try:
                out += (self.root / name).read_bytes().decode("utf-8", "replace") + "\n"
            except OSError:
                pass
        return out


def load_catalog(profiles_file=None):
    path = profiles_file or REPO / "out/runtime/unreal-profiles.json"
    data = json.loads(Path(path).read_text())["tasks"]
    return {tid: row["task"] for tid, row in data.items()}, data


def launch(task_id, tasks, profiles, root):
    t = tasks[task_id]
    if "?Task=" in t["map"]:
        map_name, native = t["map"].split("?Task=", 1)
    else:   # per-task map (older Urban builds): the map itself is the task; no ?Task= option
        map_name, native = t["map"], None
    prof = profiles.get(task_id) or profiles.get(t["map"]) or profiles.get(map_name)
    if not prof:
        raise RuntimeError(f"{task_id}: no launch profile for {t['map']}")
    if prof.get("runtime_map"):   # the launch profile's own map (what the review site / VLM harness start)
        map_name = prof["runtime_map"].split("?Task=", 1)[0]
    args = [x for x in prof.get("game_args", []) + prof.get("extra_args", [])
            if not x.lower().startswith(("-pixelstreaming", "-graphicsadapter", "-auditoripc", "-abslog"))]
    if MAXFPS:
        args = [x.replace("t.MaxFPS 30", f"t.MaxFPS {MAXFPS}") if x.startswith("-ExecCmds=") else x for x in args]
    remote_task = prof.get("remote_task")     # IPC-fixed Urban builds: task id via -AuditorRemoteTask, map = the per-task map itself
    backend = TaskBackend(prof["binary"], map_name, native, args, root, label=task_id, remote_task=remote_task)
    return backend, map_name, native or remote_task, prof


def small_jpeg_png(png_bytes, size=(192, 192)):
    img = Image.open(io.BytesIO(png_bytes)).convert("RGB")
    buf = io.BytesIO(); img.resize(size, Image.BILINEAR).save(buf, "JPEG", quality=85)
    return base64.b64encode(buf.getvalue()).decode()


def run_episode(p2p, task_id, tasks, profiles, ticks, dt_ms, record_every, text, out_dir, state_root, recover=True, idle_nudge=0):
    out_dir.mkdir(parents=True, exist_ok=True)
    t_wall = time.time()
    backend, map_name, native, prof = launch(task_id, tasks, profiles, state_root)
    try:
        state = backend.exchange("reset", map=map_name, task=native, seed=0) if native else backend.exchange("reset", map=map_name, seed=0)
        t_load = time.time() - t_wall
        for f in state.get("frames", []):
            (backend.root / f["file"]).unlink(missing_ok=True)
        keys_seen = sorted(k for k in state if k not in ("frames", "request_id"))
        start_check = None
        if prof.get("policy"):   # the game must have teleported the pawn to the policy's frozen spawn (AUDITOR_EXPLORATION_READY in its log)
            pol = prof["policy"]; pos0 = state.get("position_cm") or state.get("camera_position_cm") or [0, 0, 0]
            yaw0 = state.get("yaw_degree", state.get("yaw", 0)) or 0
            d2 = ((pos0[0] - pol["spawn"][0]) ** 2 + (pos0[1] - pol["spawn"][1]) ** 2) ** 0.5
            dyaw = abs((yaw0 - pol["yaw"] + 180) % 360 - 180)
            log_lines = [l for l in backend.log_text().splitlines() if "AUDITOR_EXPLORATION" in l]
            start_check = {"pos": pos0, "spawn": pol["spawn"], "dist_cm": round(d2, 1), "yaw": yaw0, "policy_yaw": pol["yaw"], "dyaw": round(dyaw, 1),
                           "ready": any("AUDITOR_EXPLORATION_READY" in l for l in log_lines), "log": [l.split("]")[-1].strip()[:200] for l in log_lines][:3]}
            ok = d2 <= 30 and dyaw <= 2 and start_check["ready"]
            print(f"{task_id}: start check {'OK' if ok else 'MISMATCH'} dist {d2:.0f} cm dyaw {dyaw:.1f} ready={start_check['ready']}", flush=True)
            if not ok and os.environ.get("VLA_UE_STRICT_START", "1") == "1":
                raise APIError(500, f"exploration policy not applied: {start_check}")
        backend.freeze()
        p2p.reset()
        pose_keys = [k for k in ("position_cm", "camera_position_cm", "yaw_degree", "look_degree", "simulation_time", "world_time", "actual_distance_cm", "result", "paused") if k in state]
        poses, frame_files = [], []
        acc_yaw = acc_pitch = 0.0
        action = {"keys": [], "buttons": [], "dx": 0, "dy": 0}
        stuck = 0; recovery = []; n_recoveries = 0; n_steps = 0; ignored = {"a": 0, "d": 0, "Space": 0}
        idle = 0; n_nudges = 0
        png = backend.png()
        for t in range(ticks):
            if recovery:
                act, is_rec = recovery.pop(0), True
            else:
                keys = [KEYMAP[k] for k in action["keys"] if k in KEYMAP]
                for k in ("a", "d", "Space"):
                    if k in action["keys"]: ignored[k] += 1
                dx = max(-MAX_MOUSE_PX, min(MAX_MOUSE_PX, action["dx"])); dy = max(-MAX_MOUSE_PX, min(MAX_MOUSE_PX, action["dy"]))
                act, is_rec = {"keys": keys, "mouseDx": dx, "mouseDy": dy}, False
            # --- convert the tick into Unreal steps (turn / look / move / idle) ---
            acc_yaw += act.get("mouseDx", 0) * DEG_PER_PX
            acc_pitch += act.get("mouseDy", 0) * DEG_PER_PX
            steps = []
            if abs(acc_yaw) >= 1.0:
                d = int(round(acc_yaw)); d = max(-360, min(360, d)); steps.append(("turn", d)); acc_yaw -= d
            if abs(acc_pitch) >= 1.0:
                d = int(round(acc_pitch)); d = max(-80, min(80, d)); steps.append(("look", d)); acc_pitch -= d
            fwd = ("KeyW" in act["keys"]) - ("KeyS" in act["keys"])
            if fwd > 0: steps.append(("move_up", act.get("cm", WALK_CM_PER_TICK)))
            elif fwd < 0: steps.append(("move_down", act.get("cm", WALK_CM_PER_TICK)))
            if not steps: steps.append(("idle", dt_ms / 1000.0))
            moved = 0.0; respawned = False; last = state
            backend.thaw()
            for name, value in steps:
                last = backend.exchange(name, value=value); n_steps += 1
                for f in last.get("frames", []):
                    (backend.root / f["file"]).unlink(missing_ok=True)
                if name.startswith("move"): moved += float(last.get("actual_distance_cm", 0) or 0)
                if last.get("result") not in (None, "ok", "moved", "blocked", "done") and last.get("outcome") is None: pass
            state = last
            backend.freeze()   # no rendering while the policy thinks
            png = backend.png()
            pos = state.get("position_cm") or state.get("camera_position_cm")
            poses.append({"t": t, "pos_cm": pos, "yaw": state.get("yaw_degree", state.get("yaw", state.get("rotation_degree"))),
                          "pitch": state.get("look_degree", state.get("pitch_degree")), "moved_cm": round(moved, 2),
                          "keys": act["keys"], "dx": act.get("mouseDx", 0), "dy": act.get("mouseDy", 0), "steps": [s[0] for s in steps],
                          "recovery": is_rec, "nudge": bool(act.get("nudge")), "sim": state.get("simulation_time"), "world_time": state.get("world_time"), "result": state.get("result")})
            if t % record_every == 0:
                fn = f"f{t:05d}.jpg"
                Image.open(io.BytesIO(png)).convert("RGB").save(out_dir / fn, "JPEG", quality=85)
                frame_files.append(fn)
            if recover and not is_rec:
                stuck = stuck + 1 if ("KeyW" in act["keys"] and moved < 1.0) else 0
                if stuck >= 40:
                    sgn = 1 if n_recoveries % 2 == 0 else -1
                    recovery = [{"keys": ["KeyS"], "mouseDx": 0, "mouseDy": 0}] * 10 + [{"keys": [], "mouseDx": sgn * 105, "mouseDy": 0}] * 12
                    n_recoveries += 1; stuck = 0
            if idle_nudge and not is_rec and not recovery:   # idle-nudge wrapper, same rule as agent/vla/vla_explore.py
                moving = bool(set(act["keys"]) & {"KeyW", "KeyS", "KeyA", "KeyD"}) or abs(act.get("mouseDx", 0)) + abs(act.get("mouseDy", 0)) >= 4
                idle = 0 if moving else idle + 1
                if idle >= idle_nudge:
                    sgn = 1 if n_nudges % 2 == 0 else -1
                    recovery = [{"keys": [], "mouseDx": sgn * 105, "mouseDy": 0, "nudge": True}] * 12
                    if n_nudges % 2 == 1: recovery += [{"keys": ["KeyW"], "mouseDx": 0, "mouseDy": 0, "nudge": True}] * 10
                    n_nudges += 1; idle = 0
                p2p.reset()   # re-sample the policy's mode: an idle mode persists through view changes (its own no-op history)
            action = p2p.act(small_jpeg_png(png), text)
        (out_dir / "poses.jsonl").write_text("\n".join(json.dumps(p) for p in poses))
        meta = dict(task=task_id, map=map_name, binary=prof["binary"], build_sha256=prof.get("build_sha256"), kind="vla_explore_ue",
                    policy_version=prof.get("policy_version"), policy=prof.get("policy"), task_revision=(tasks[task_id].get("revision")), start_check=start_check,
                    game_args=[x for x in prof.get("game_args", []) + prof.get("extra_args", [])], render_res=RES, freeze=FREEZE,
                    model="open-p2p-1.2B", ticks=ticks, dt_ms=dt_ms, record_every=record_every, text=text,
                    n_recoveries=n_recoveries, n_nudges=n_nudges, idle_nudge=idle_nudge, unreal_steps=n_steps, ignored_keys=ignored, sim_seconds=round(ticks * dt_ms / 1000, 1),
                    frames=frame_files, observation_keys=keys_seen, pose_keys=pose_keys, load_s=round(t_load, 1), wall_s=round(time.time() - t_wall, 1))
        (out_dir / "meta.json").write_text(json.dumps(meta, indent=1))
        try:
            import imageio.v2 as imageio
            import numpy as np
            w = imageio.get_writer(out_dir / "video.mp4", fps=int(1000 / dt_ms / record_every * 2), codec="libx264", quality=7, macro_block_size=None)
            for fn in frame_files: w.append_data(np.asarray(Image.open(out_dir / fn)))
            w.close()
        except Exception as e:
            print("video assembly failed:", e)
        print(f"{task_id}: {ticks} ticks, {n_steps} unreal steps, {len(frame_files)} frames, {n_recoveries} recoveries, "
              f"load {t_load:.0f} s, {time.time() - t_wall:.0f} s wall", flush=True)
    finally:
        backend.close()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tasks", required=True, help="comma-separated task ids, or @file with one id per line")
    ap.add_argument("--ticks", type=int, default=1200)
    ap.add_argument("--dt-ms", type=int, default=50)
    ap.add_argument("--record-every", type=int, default=10)
    ap.add_argument("--text", default="Explore this place. Walk around and look at everything.")
    ap.add_argument("--no-text", action="store_true")
    ap.add_argument("--tag", default="vla-ue")
    ap.add_argument("--size", default="1200M")
    ap.add_argument("--gpu", default="0")
    ap.add_argument("--eager", action="store_true")
    ap.add_argument("--p2p-host", default=None, help="run the P2P server on this ssh host (remote inference)")
    ap.add_argument("--no-recover", action="store_true")
    ap.add_argument("--idle-nudge", type=int, default=0, help="scripted look-around after this many idle ticks (0 = off)")
    ap.add_argument("--skip-done", action="store_true")
    ap.add_argument("--claim", action="store_true", help="several drivers over the same list: claim a task atomically (runs/<tag>/<task>.claim) before running it")
    ap.add_argument("--state-root", default=str(REPO / "runs" / "ue-state"))
    ap.add_argument("--profiles", default=str(REPO / "out/runtime/unreal-profiles.json"), help="Installed Unreal task profiles")
    args = ap.parse_args()
    ids = [x.strip() for x in (Path(args.tasks[1:]).read_text().split() if args.tasks.startswith("@") else args.tasks.split(",")) if x.strip()]
    text = None if args.no_text else args.text
    tasks, profiles = load_catalog(args.profiles)
    missing = [i for i in ids if i not in tasks]
    if missing: raise SystemExit(f"unknown tasks: {missing}")
    state_root = Path(args.state_root); state_root.mkdir(parents=True, exist_ok=True)
    p2p = P2PClient(gpu=args.gpu, size=args.size, eager=args.eager, host=args.p2p_host)
    try:
        for task_id in ids:
            out_dir = REPO / "runs" / args.tag / task_id
            if args.skip_done and (out_dir / "meta.json").exists():
                print(f"{task_id}: done, skipped"); continue
            if (REPO / "runs" / args.tag / "STOP").exists():   # graceful stop between episodes (touch runs/<tag>/STOP)
                print("STOP file present, exiting before the next task", flush=True); break
            if args.claim:   # same rule as agent/vla/vla_explore.py: first driver to create the marker runs the task
                claim = out_dir.parent / (out_dir.name + ".claim"); out_dir.parent.mkdir(parents=True, exist_ok=True)
                try: os.close(os.open(claim, os.O_CREAT | os.O_EXCL | os.O_WRONLY))
                except FileExistsError: print(f"{task_id}: claimed by another driver, skipped"); continue
            try:
                run_episode(p2p, task_id, tasks, profiles, args.ticks, args.dt_ms, args.record_every, text, out_dir, state_root, recover=not args.no_recover, idle_nudge=args.idle_nudge)
            except APIError as e:
                print(f"{task_id}: FAILED {e.status} {e.message}", flush=True)
                out_dir.mkdir(parents=True, exist_ok=True); (out_dir / "error.txt").write_text(f"{e.status} {e.message}\n")
            except (KeyboardInterrupt, BrokenPipeError):
                raise
            except (Exception, SystemExit) as e:   # launch/config errors: record and go on with the next task
                import traceback
                print(f"{task_id}: FAILED {type(e).__name__}: {e}", flush=True)
                out_dir.mkdir(parents=True, exist_ok=True); (out_dir / "error.txt").write_text(f"{type(e).__name__}: {e}\n{traceback.format_exc()}")
                try: p2p.reset()
                except Exception: pass
    finally:
        p2p.close()


if __name__ == "__main__":
    main()
