#!/usr/bin/env python3
"""Embed Poly Haven texture sets as JPEG data URLs in a TypeScript module for the Vite build.
Usage: make_textures_module.py --assets assets/fable/textures --out src/fable/upstream/src/assets/textures.ts
"""
import argparse, base64, io, pathlib
from PIL import Image

SETS = {  # id: (max size, jpeg quality diffuse, quality normal)
    "leafy_grass": (1024, 82, 85), "forest_ground_04": (1024, 82, 85), "rock_face_03": (1024, 82, 85),
    "rock_surface": (1024, 82, 85), "snow_02": (1024, 80, 82), "pine_bark": (1024, 82, 85),
}


def jpeg_data_url(path, size, q):
    im = Image.open(path).convert("RGB")
    if max(im.size) > size:
        im = im.resize((size, size), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "JPEG", quality=q, optimize=True)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def mean_linear_luminance(path):
    """Mean luminance of the sRGB image in linear light (used to normalise texture brightness)."""
    import numpy as np
    im = np.asarray(Image.open(path).convert("RGB").resize((256, 256)), dtype=np.float64) / 255.0
    lin = np.where(im <= 0.04045, im / 12.92, ((im + 0.055) / 1.055) ** 2.4)
    lum = lin[..., 0] * 0.2126 + lin[..., 1] * 0.7152 + lin[..., 2] * 0.0722
    return float(lum.mean())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--assets", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    root = pathlib.Path(a.assets)
    lines = ["// Generated by make_textures_module.py — Poly Haven CC0 texture sets (1k JPEG data URLs).",
             "export interface TextureSet { diff: string; nor: string; meanLum: number }",
             "export const TEXTURE_SETS: Record<string, TextureSet> = {"]
    total = 0
    for tid, (size, qd, qn) in SETS.items():
        d = root / tid
        diff = jpeg_data_url(d / "Diffuse.jpg", size, qd)
        nor = jpeg_data_url(d / "nor_gl.jpg", size, qn)
        mean = mean_linear_luminance(d / "Diffuse.jpg")
        entry = f"  {tid}: {{ diff: '{diff}', nor: '{nor}', meanLum: {mean:.4f} }},"
        print(f"{tid}: mean linear luminance {mean:.3f}")
        total += len(entry)
        lines.append(entry)
    lines.append("};")
    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({total/1e6:.1f} MB)")


if __name__ == "__main__":
    main()
